// Reuseable constant values go here

export const genders = ["Male", "Female"];

export const languageProficiencies = [
  "Conversational",
  "Professional",
  "Native",
];

export const languages = [
  "Arabic",
  "Azerbaijani",
  "Awadhi",
  "Balochi",
  "Belarusian",
  "Bengali",
  "Bhojpuri",
  "Burmese",
  "Cebuano",
  "Chewa",
  "Czech",
  "Deccan",
  "Dutch",
  "Egyptian Arabic",
  "English",
  "French",
  "Fula",
  "German",
  "Gujarati",
  "Hindi",
  "Indonesian",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Korean",
  "Maithili",
  "Malay",
  "Malayalam",
  "Mandarin Chinese",
  "Marathi",
  "Oriya",
  "Panjabi (Eastern)",
  "Panjabi (Western)",
  "Persian",
  "Portuguese",
  "Russian",
  "Spanish",
  "Swahili",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
  "Wu Chinese",
  "Xiang Chinese",
  "Yoruba",
  "Zhuang",
];

export const nationalities = [
  "Malaysian",
  "Afghan",
  "Algerian",
  "American",
  "Argentine",
  "Australian",
  "Austrian",
  "Bangladeshi",
  "Belgian",
  "Bolivian",
  "Brazilian",
  "British",
  "Bulgarian",
  "Burmese",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Congolese",
  "Costa Rican",
  "Cuban",
  "Czech",
  "Danish",
  "Dutch",
  "Ecuadorian",
  "Egyptian",
  "Ethiopian",
  "Filipino",
  "Finnish",
  "French",
  "German",
  "Ghanaian",
  "Greek",
  "Guatemalan",
  "Haitian",
  "Honduran",
  "Hungarian",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kenyan",
  "Korean",
  "Kuwaiti",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Mexican",
  "Moroccan",
  "Nepalese",
  "Nigerian",
  "Norwegian",
  "Pakistani",
  "Palestinian",
  "Panamanian",
  "Paraguayan",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Romanian",
  "Russian",
  "Salvadoran",
  "Saudi Arabian",
  "Senegalese",
  "Singaporean",
  "Somali",
  "South African",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Swedish",
  "Swiss",
  "Not Listed",
];

export const malaysianEducationalInstitutions = [
  "Asia Pacific University of Technology & Innovation (APU)",
  "HELP University",
  "INTI International University",
  "International Islamic University Malaysia (IIUM)",
  "KDU University College",
  "Kolej Poly-Tech Mara (KPTM)",
  "Kolej Universiti Islam Antarabangsa Selangor (KUIS)",
  "Limkokwing University of Creative Technology",
  "Management & Science University (MSU)",
  "Monash University Malaysia",
  "Multimedia University (MMU)",
  "Nilai University",
  "Open University Malaysia (OUM)",
  "Penang Medical College (PMC)",
  "Quest International University Perak (QIUP)",
  "SEGi University",
  "Sunway University",
  "Taylor's University",
  "Tunku Abdul Rahman University College (TAR UC)",
  "UCSI University",
  "UIAM - Universiti Islam Antarabangsa Malaysia",
  "UM - University of Malaya",
  "UMK - Universiti Malaysia Kelantan",
  "UMS - Universiti Malaysia Sabah",
  "UMT - Universiti Malaysia Terengganu",
  "UMP - Universiti Malaysia Pahang",
  "UniMAP - Universiti Malaysia Perlis",
  "UNIMAS - Universiti Malaysia Sarawak",
  "UniSZA - Universiti Sultan Zainal Abidin",
  "UPM - Universiti Putra Malaysia",
  "UPSI - Universiti Pendidikan Sultan Idris",
  "USIM - Universiti Sains Islam Malaysia",
  "USM - Universiti Sains Malaysia",
  "UTAR - Universiti Tunku Abdul Rahman",
  "UTM - Universiti Teknologi Malaysia",
  "UTP - Universiti Teknologi PETRONAS",
  "UUM - Universiti Utara Malaysia",
  "UUMC - University of Malaya Medical Centre",
  "Xiamen University Malaysia",
];

export const educationLevels = [
  "Secondary School",
  "Pre-University (A-Levels, Foundation, Diploma or equivalent)",
  "Undergraduate (Bachelor's Degree or equivalent)",
  "Postgraduate (Master's Degree or equivalent or higher)",
  "Other",
];
